import { blit } from "./key.mjs";

/**
 * The atlas: one action per row, every frame the same size, so a CSS steps()
 * animation can walk a row and a game can index frames by number. With it, the
 * metadata engines read: the TexturePacker JSON hash with Aseprite's frame tags
 * and durations (what Phaser, PixiJS, Godot's importers and most others take), a
 * CSS sheet with a keyframe animation per action, and a C header with the frame
 * table and a tiny player, for raylib and anything else that speaks C.
 */

const blank = (width, height) => ({ width, height, data: new Uint8Array(width * height * 4) });

/**
 * Lays actions out one per row. `actions` is [{ name, frames: [image], fps }],
 * every image the same width and height. Returns the atlas image, each frame's
 * placement in order, and each action's range of frame numbers.
 */
export function packActions(actions, { padding = 0 } = {}) {
  if (!actions.length || !actions[0].frames.length) throw new Error("an atlas needs at least one action with one frame");
  const fw = actions[0].frames[0].width;
  const fh = actions[0].frames[0].height;
  for (const a of actions) for (const f of a.frames) if (f.width !== fw || f.height !== fh) throw new Error(`every frame must be ${fw}x${fh}; ${a.name} has a ${f.width}x${f.height} frame`);
  const columns = Math.max(...actions.map((a) => a.frames.length));
  const width = columns * (fw + padding) - padding;
  const height = actions.length * (fh + padding) - padding;
  if (width > 8192 || height > 8192) throw new Error(`the atlas would be ${width}x${height}; keep it under 8192 on a side`);
  const image = blank(width, height);
  const placements = [];
  const ranges = [];
  let index = 0;
  actions.forEach((a, row) => {
    const from = index;
    a.frames.forEach((f, col) => {
      const x = col * (fw + padding);
      const y = row * (fh + padding);
      blit(image, f, x, y);
      placements.push({ name: `${a.name}_${col}`, action: a.name, index, x, y, width: fw, height: fh, durationMs: Math.round(1000 / (a.fps ?? 8)) });
      index++;
    });
    ranges.push({ name: a.name, from, to: index - 1, fps: a.fps ?? 8, row });
  });
  return { image, placements, ranges, frame: { width: fw, height: fh }, columns, rows: actions.length };
}

/** The TexturePacker JSON hash, with Aseprite's frameTags and per-frame durations. */
export function atlasJSON(atlas, { file = "atlas.png", app = "onmodel", version = "0.1.0" } = {}) {
  const frames = {};
  for (const p of atlas.placements) {
    frames[p.name] = {
      frame: { x: p.x, y: p.y, w: p.width, h: p.height },
      rotated: false,
      trimmed: false,
      spriteSourceSize: { x: 0, y: 0, w: p.width, h: p.height },
      sourceSize: { w: p.width, h: p.height },
      duration: p.durationMs,
    };
  }
  return {
    frames,
    meta: {
      app,
      version,
      image: file,
      format: "RGBA8888",
      size: { w: atlas.image.width, h: atlas.image.height },
      scale: "1",
      frameTags: atlas.ranges.map((r) => ({ name: r.name, from: r.from, to: r.to, direction: "forward", fps: r.fps })),
    },
  };
}

const cssName = (s) => String(s).replace(/[^a-zA-Z0-9_-]+/g, "-");

/** A stylesheet: a base class for the sprite and a steps() animation per action along its row. */
export function atlasCSS(atlas, { file = "atlas.png", prefix = "om", pixelated = true } = {}) {
  const { width: fw, height: fh } = atlas.frame;
  const lines = [
    `/* Generated by onmodel. One action per row of ${file}; frames ${fw}x${fh}. */`,
    `.${prefix}-sprite { width: ${fw}px; height: ${fh}px; background: url("${file}") no-repeat 0 0;${pixelated ? " image-rendering: pixelated;" : ""} }`,
  ];
  for (const r of atlas.ranges) {
    const n = r.to - r.from + 1;
    const y = -r.row * fh;
    const name = `${prefix}-${cssName(r.name)}`;
    const seconds = Math.round((n / r.fps) * 1000) / 1000;
    lines.push(`.${name} { background-position: 0px ${y}px; animation: ${name} ${seconds}s steps(${n}) infinite; }`);
    lines.push(`@keyframes ${name} { from { background-position: 0px ${y}px; } to { background-position: ${-n * fw}px ${y}px; } }`);
  }
  return lines.join("\n") + "\n";
}

const cName = (s) =>
  String(s)
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_|_$/g, "") || "ACTION";

/** A C header: the frame table, the action table, an enum, and a player that picks the frame for a time. */
export function atlasHeader(atlas, { file = "atlas.png", guard = "OM_ATLAS_H", prefix = "OM" } = {}) {
  const { width: fw, height: fh } = atlas.frame;
  // C convention: types in CamelCase (OmFrame), constants and macros in capitals (OM_FRAMES).
  const Type = prefix[0].toUpperCase() + prefix.slice(1).toLowerCase();
  const frames = atlas.placements.map((p) => `    { ${p.x}, ${p.y}, ${p.width}, ${p.height} }`).join(",\n");
  const actions = atlas.ranges.map((r) => `    { "${r.name}", ${r.from}, ${r.to}, ${r.fps.toFixed(1)}f }`).join(",\n");
  const names = atlas.ranges.map((r, i) => `    ${prefix}_${cName(r.name)} = ${i}`).join(",\n");
  return `/* Generated by onmodel. Frames of ${file}, each ${fw}x${fh}, one action per row. */
#ifndef ${guard}
#define ${guard}

typedef struct { int x, y, w, h; } ${Type}Frame;
typedef struct { const char *name; int from, to; float fps; } ${Type}Action;

static const int ${prefix}_FRAME_W = ${fw};
static const int ${prefix}_FRAME_H = ${fh};
static const int ${prefix}_FRAME_COUNT = ${atlas.placements.length};
static const int ${prefix}_ACTION_COUNT = ${atlas.ranges.length};

static const ${Type}Frame ${prefix}_FRAMES[${atlas.placements.length}] = {
${frames}
};

static const ${Type}Action ${prefix}_ACTIONS[${atlas.ranges.length}] = {
${actions}
};

enum {
${names}
};

/* The frame of an action at time t seconds, looping. */
static inline int ${prefix.toLowerCase()}_frame_at(const ${Type}Action *a, float t) {
    int n = a->to - a->from + 1;
    int i = (int)(t * a->fps) % n;
    if (i < 0) i += n;
    return a->from + i;
}

#endif
`;
}
